import type { Transport } from '@modelcontextprotocol/sdk/shared/transport.js'
import type { JSONRPCMessage } from '@modelcontextprotocol/sdk/types.js'

/**
 * Minimal MCP server Transport bridging one inbound TCP/WebSocket session to
 * an `McpServer` instance. Framing and session lifecycle stay with the host
 * transport (`TcpTransport`/`WebSocketTransport`); this class only adapts the
 * SDK's `Transport` contract.
 *
 * Notifications (no `id`) are dispatched into the SDK server, which never
 * produces a response for them — replies are generated by the SDK for
 * requests only.
 */
export class SessionMcpTransport implements Transport {
  sessionId?: string
  onclose?: () => void
  onerror?: (error: Error) => void
  onmessage?: (message: JSONRPCMessage) => void

  constructor(
    private readonly sendFn: (message: JSONRPCMessage) => boolean,
    private readonly closeFn: () => void,
    sessionId?: string,
  ) {
    this.sessionId = sessionId
  }

  async start(): Promise<void> {
    // The host transport is already connected; nothing to initialize.
  }

  async send(message: JSONRPCMessage): Promise<void> {
    if (!this.sendFn(message)) {
      throw new Error(`session ${this.sessionId ?? 'unknown'} is closed`)
    }
  }

  async close(): Promise<void> {
    this.closeFn()
  }

  /** Deliver a message received by the host transport into the MCP server. */
  dispatch(message: unknown): void {
    this.onmessage?.(message as JSONRPCMessage)
  }
}
